// Event type constants — única fuente de verdad para todos los tipos de evento del sistema.
// Usar estas constantes en lugar de strings literales en todo el código.

export const EVENT_TYPES = {
  DOCUMENT_PREPARED: 'DOCUMENT_PREPARED',
  DOCUMENT_TX_SUBMITTED: 'DOCUMENT_TX_SUBMITTED',
  DOCUMENT_CREATED: 'DOCUMENT_CREATED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_ARCHIVED: 'DOCUMENT_ARCHIVED',
  DOCUMENT_UNARCHIVED: 'DOCUMENT_UNARCHIVED',
  DOCUMENT_ROLLBACK: 'DOCUMENT_ROLLBACK',

  VERSION_PREPARED: 'VERSION_PREPARED',
  VERSION_TX_SUBMITTED: 'VERSION_TX_SUBMITTED',
  VERSION_RESTORED: 'VERSION_RESTORED',
  VERSION_RESTORE_PREPARED: 'VERSION_RESTORE_PREPARED',
  VERSION_RESTORE_ROLLBACK: 'VERSION_RESTORE_ROLLBACK',
  VERSION_ROLLBACK: 'VERSION_ROLLBACK',
  OPERATIONAL_VERSION_TX_SUBMITTED: 'OPERATIONAL_VERSION_TX_SUBMITTED',
  OPERATIONAL_VERSION_CHANGED: 'OperationalVersionChanged',

  SHARE_PREPARED: 'SHARE_PREPARED',
  SHARE_CONFIRMED: 'SHARE_CONFIRMED',
  SHARE_REVOKE_PREPARED: 'SHARE_REVOKE_PREPARED',
  SHARE_REVOKED: 'SHARE_REVOKED',

  SIGNATURE_PREPARED: 'SIGNATURE_PREPARED',
  SIGNATURE_TX_SUBMITTED: 'SIGNATURE_TX_SUBMITTED',

  TRANSFER_PREPARED: 'TRANSFER_PREPARED',
  TRANSFER_CONFIRMED: 'TRANSFER_CONFIRMED',

  ADMIN_ROLE_GRANTED: 'AdminRoleGranted',
  ADMIN_ROLE_REVOKED: 'AdminRoleRevoked',
  DOCUMENT_TRANSFERRED: 'DocumentTransferred',
} as const;

export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];
