skinparam backgroundColor white
skinparam monochrome true
skinparam shadowing false
skinparam linetype ortho
skinparam packageStyle rectangle
skinparam classAttributeIconSize 0
skinparam DefaultFontName Arial
skinparam DefaultFontSize 12
