@startgantt
skinparam backgroundColor White
printscale daily zoom 2
Project starts 2025-12-08

-- Fase Inicio - Iteracion 2 --
[T5: Definicion del alcance y objetivos] lasts 2 days
then [T6: Identificacion de actores y UC] lasts 2 days
[T7: Seleccion del stack tecnologico] lasts 2 days
[T7: Seleccion del stack tecnologico] starts at [T5: Definicion del alcance y objetivos]'s end
then [T8: Elaboracion de la planificacion] lasts 2 days
[M9: Fin Iteracion 2 - Inicio] happens at [T8: Elaboracion de la planificacion]'s end
[M9: Fin Iteracion 2 - Inicio] is colored in Gold/DarkRed
@endgantt
