@startgantt
skinparam backgroundColor White
printscale daily zoom 3
Project starts 2025-12-15

[Iteracion 1 - Fase Elaboracion] lasts 15 days

[Especificacion de requisitos] lasts 10 days
[Especificacion de requisitos] starts at [Iteracion 1 - Fase Elaboracion]'s start
[T10: Especificacion de requisitos funcionales] lasts 3 days
[T10: Especificacion de requisitos funcionales] starts at [Especificacion de requisitos]'s start
[T11: Especificacion de requisitos no funcionales] lasts 3 days
[T11: Especificacion de requisitos no funcionales] starts at [T10: Especificacion de requisitos funcionales]'s end
[T12: Especificacion completa de casos de uso] lasts 4 days
[T12: Especificacion completa de casos de uso] starts at [T11: Especificacion de requisitos no funcionales]'s end

[Diseno conceptual] lasts 5 days
[Diseno conceptual] starts at [Especificacion de requisitos]'s end
[T13: Diseno de la arquitectura general] lasts 3 days
[T13: Diseno de la arquitectura general] starts at [Diseno conceptual]'s start
[T14: Diseno del modelo de datos ER] lasts 2 days
[T14: Diseno del modelo de datos ER] starts at [T13: Diseno de la arquitectura general]'s end

[M15: Fin Iteracion 1 - Elaboracion] happens at [Iteracion 1 - Fase Elaboracion]'s end
[M15: Fin Iteracion 1 - Elaboracion] is colored in Gold/DarkRed
@endgantt
