@startuml
!include _sequence-bce-style.puml

title UC-0005: Eliminar Wallet (Análisis)

actor "Usuario logueado" as Actor
boundary "Interfaz Perfil" as BF
control "Controlador Wallet" as CW
entity "Wallet" as EW


Actor -> BF : 1. Selecciona wallet a eliminar
BF -> CW : 2. Peticion de eliminacion
CW -> EW : 3. Verifica que no es wallet primaria
EW --> CW : verificacion OK

CW -> EW : 4. Elimina wallet
EW --> CW : wallet eliminada

CW --> BF : 5. Confirmacion
BF --> Actor : 6. Lista de wallets actualizada

@enduml


