@startuml
!include _sequence-bce-style.puml

title UC-0030: Descargar Version Especifica (Analisis BCE)

actor "Usuario logueado" as Actor
boundary "Interfaz Versiones" as BF
control "Controlador Version" as CV
entity "Version" as EV


Actor -> BF : 1. Selecciona version a descargar
BF -> CV : 2. Peticion de descarga
CV -> EV : 3. Recupera CID de la version
EV --> CV : CID de la version


CV -> CV : 4. Verifica integridad del contenido
note right : Control contrasta hash del contenido recuperado con el hash registrado

CV --> BF : 5. Archivo de la version
BF --> Actor : 6. Inicia descarga del archivo

@enduml


