@startuml
!include _sequence-bce-style.puml

title UC-0011: Cambiar Contrasena (Análisis)

actor "Usuario logueado" as Actor
boundary "Interfaz Perfil" as BF
control "Controlador Autenticacion" as CG
entity "Usuario" as EU


Actor -> BF : 1. Introduce contrasena actual y nueva
BF -> CG : 2. Envia datos de cambio
CG -> EU : 3. Verifica contrasena actual
EU --> CG : verificacion de coincidencia

alt Contrasena actual correcta
  CG -> CG : 4. Genera nuevo hash de contrasena
  CG -> EU : 5. Actualiza contrasena
  EU --> CG : contrasena actualizada
  CG --> BF : 6. Confirmacion
  BF --> Actor : 7. Muestra exito
else Contrasena actual incorrecta
  CG --> BF : 8. Error de verificacion
  BF --> Actor : 9. Muestra error
end

@enduml


