@startuml
!include _structure-style.puml
left to right direction
title Casos de uso - Administracion

actor "Administrador" as ADMIN

rectangle "Modulo de administracion" {
  usecase "UC-0038: Listar Usuarios" as UC38
  usecase "UC-0039: Gestionar Roles" as UC39
}

UC38 -[hidden]down-> UC39

ADMIN --> UC38
ADMIN --> UC39
@enduml
