@startuml
!include _structure-style.puml
left to right direction
title Casos de uso - Firmas

actor "Usuario" as USER
actor "Blockchain" as SC

rectangle "Modulo de firmas" {
  usecase "UC-0027: Firmar Documento" as UC27
  usecase "UC-0028: Ver Firmas de un Documento" as UC28
  usecase "UC-0029: Verificar Firma del Usuario" as UC29
}

UC27 -[hidden]down-> UC28
UC28 -[hidden]down-> UC29

USER --> UC27
USER --> UC28
USER --> UC29

SC --> UC27
SC --> UC29
@enduml
