@startuml
!include _structure-style.puml
left to right direction

actor "Usuario" as USER
actor "Blockchain" as SC

rectangle "Gestion de Firmas" {
  usecase "UC-0030: Firmar Documento" as UC34
  usecase "UC-0031: Ver Firmas de un Documento" as UC35
  usecase "UC-0032: Verificar Firma en Blockchain" as UC36
}

UC34 -[hidden]down-> UC35
UC35 -[hidden]down-> UC36

USER --> UC34
USER --> UC35
USER --> UC36

SC --> UC34
SC --> UC36
@enduml
